name: Update List

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - 'main'

jobs:
  checks:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install deps
        run: cd scripts && pnpm i

      - name: Update the list
        run: node ./scripts/update.js
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
